// Constants for Actions

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const ADD_RECIPE = "ADD_RECIPE";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INGREDIENT_IS_LOADING = "INGREDIENT_IS_LOADING";
export const INGREDIENT_LOADING_ERRORED = "INGREDIENT_LOADING_ERRORED";
export const INGREDIENTS_FETCHED = "INGREDIENTS_FETCHED";
